# Getting started with Python - Lecture 5

This is a Jupyter Notebook. It contains both text and Python code. You can run the code cells in this notebook to see the output.

## Arithmetic Operations

In [ ]:
2 + 3

5

There are multiple ways to *run* a cell: click the `Play` button in the toolbar, press `Shift + Enter`, or press `Ctrl + Enter`.

In [ ]:
# If you have multiple lines of code, you can run them all at once. 
# If you want see the output of each line, you can use the print() function. 
# For example:

print(2 + 3)  # Addition
print(5 - 2)  # Subtraction
print(4 * 3)  # Multiplication
print(10 / 2) # Division

5
3
12
5.0

## Storing Values in Variables

In [6]:
x = 10
print(x)  # Output: 10

10

In [ ]:
# adding variables
y = 3
print(x + y)  # Output: 13

13

Notice that we can store values in variables and use them later. We assigned `10` to the variable `x` two cells above, then used `x` in the following cell. If you want to clear all of the variables, you can restart the kernel by clicking `Kernel` in the menu bar and selecting `Restart Kernel`.

## Storing Strings in Variables

A string is a sequence of characters. In Python, we can store strings in variables just like we do with numbers. Strings are enclosed in either single quotes (`'`) or double quotes (`"`).

In [8]:
my_string = "Hello, World!"

In [10]:
# example operations on strings
print(my_string.upper())  # Convert to uppercase
print(my_string.lower())  # Convert to lowercase
print(my_string[:5])  # Slice the string to get "Hello"

HELLO, WORLD!
hello, world!
Hello

## Printing Output

f-strings allow you to embed expressions inside strings, using curly braces `{}`.

In [25]:
print(f'The value of x is {x} and the value of y is {y}.')  # Using f-strings to embed variables in strings

The value of x is 10 and the value of y is 3.

## Logical Statements

Logical statements allow us to make decisions in our code and evaluate to either `True` or `False`. We can use logical operators such as `and`, `or`, and `not` to combine multiple conditions.

In [19]:
2 > 1

True

In [20]:
print(1 >= 2) # 1 is greater than or equal to 2? False
print(1 < 2)  # 1 is less than 2? True
print(x == 10) # x is equal to 10? True
print(my_string != "Hello") # my_string is not equal to "Hello"? True

False
True
True
True

Helpful operations: 
- `==` : equal to
- `!=` : not equal to
- `>` : greater than
- `<` : less than
- `>=` : greater than or equal to
- `<=` : less than or equal to

We can also combine logical statements using `and`, `or`, and `not`. 
- `and` : returns `True` if both statements are true
- `or` : returns `True` if at least one statement is true
- `not` : returns `True` if the statement is false

## Using Libraries

Base Python comes with a lot of built-in functionality, but we can also use libraries to extend Python's capabilities. A library is a collection of pre-written code that we can use in our programs. We can import libraries using the `import` statement.

In [21]:
import pandas as pd # import the pandas library for data manipulation

## Reading in Data

In [22]:
df = pd.read_csv("../datasets/dining.csv") # read in a CSV file and store it as a DataFrame in a variable called df

## Using Pandas

In [23]:
# Look at the first five rows of the data
df.head(5)

         date dining_hall  swipes featured_item  week  coffee_consumed
0  2024-01-08      Brooks     108         Pasta     1               24
1  2024-01-08    McKinley     126        Burger     1               22
2  2024-01-09      Brooks     112       Chicken     1               26
3  2024-01-09    McKinley     129         Pizza     1               24
4  2024-01-10      Brooks     116         Tacos     1               27

In [26]:
# check dataset dimensions
shape = df.shape
print(f'The dataset has {shape[0]} rows and {shape[1]} columns.')  # Using f-strings to embed variables in strings

The dataset has 30 rows and 6 columns.

In [27]:
# check the types of columns
df.dtypes

date                 str
dining_hall          str
swipes             int64
featured_item        str
week               int64
coffee_consumed    int64
dtype: object

In [33]:
# we can filter rows using a logical statement
# using brackets this way is called indexing

# For example, we can filter the DataFrame to only include rows where the 'week' column is equal to 3.
df_week3 = df[df['week'] == 3] 
df_week3

          date dining_hall  swipes featured_item  week  coffee_consumed
20  2024-01-22      Brooks     132       Lasagna     3               32
21  2024-01-22    McKinley     140        Burger     3               28
22  2024-01-23      Brooks     121         Pasta     3               34
23  2024-01-23    McKinley     136       Chicken     3               29
24  2024-01-24      Brooks     128         Tacos     3               36
25  2024-01-24    McKinley     143         Pizza     3               31
26  2024-01-25      Brooks     134        Burger     3               38
27  2024-01-25    McKinley     147      Stir-Fry     3               33
28  2024-01-26      Brooks     130       Lasagna     3               40
29  2024-01-26    McKinley     150          Fish     3               35

In [34]:
# we can also filter columns using a list of column names. For example, we can select only the 'week' and 'coffee_consumed' columns from the DataFrame.
df_week_coffee = df[['week', 'coffee_consumed']]
df_week_coffee

    week  coffee_consumed
0      1               24
1      1               22
2      1               26
3      1               24
4      1               27
5      1               23
6      1               29
7      1               25
8      1               31
9      1               27
10     2               30
11     2               25
12     2               28
13     2               31
14     2               29
15     2               27
16     2               33
17     2               26
18     2               35
19     2               30
20     3               32
21     3               28
22     3               34
23     3               29
24     3               36
25     3               31
26     3               38
27     3               33
28     3               40
29     3               35